######################## Paper Information ########################################
# Personal info
paper_name: "QuIRK: Quantum-Inspired Re-uploading KAN"

organization: Arizona State University
sub_organization: School of Computing and Augmented Intelligence
preprint: True # Set true if pre-print. False otherwise

######################## Paper Resources ########################################

paper_pdf: https://arxiv.org/pdf/2510.08650 # Main PDF Link here
# supplementary_pdf: Supplementary PDF here
# code: https://github.com/MPSLab-ASU/Project_Page_Template # GitHub link here
arXiv: https://arxiv.org/abs/2510.08650 # ArXiV Publication Link Here
# IEEE: https://ieeexplore.ieee.org/document/9187262 # IEEE Publication Link Here
#ACM: ACM Publication Link Here
# Additional icon links

favicon: assets/images/MPS_Lab.ico

main_media:
    source: assets/images/Network_Full.png
    caption: QuIRK Macro architecture. Each incoming edge to a QuIRK layer is a single qubit DR circuit. The output of each hidden QuIRK layer ($h^l_u$) is then rescaled to the range [0, Ï€] creating node $h'^l_u$. The output of the network is a QuIRK layer with a single unit followed by an optional dense layer which scales the output to the desired range.

######################## DO NOT EDIT BELOW THIS LINE ########################################

# Footer
footer_show_references: true

#sass
sass:
    sass_dir: _sass
    style: compressed

plugins:
    - jekyll-seo-tag
    - jekyll-coffeescript

markdown: kramdown
permalink: pretty

exclude:
    [
        "Gemfile",
        "Gemfile.lock",
        "node_modules",
        "vendor/bundle/",
        "vendor/cache/",
        "vendor/gems/",
        "vendor/ruby/",
        "lib/",
        "scripts/",
        "docker-compose.yml",
        "README.md",
    ]
